my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from p_library import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.books_list),
    path('index/', views.index),
    path('index/book_increment/', views.book_increment),
    path('index/book_decrement/', views.book_decrement),
    path('redactions/', views.redactions),
    path('p/', include("p_library.urls"))
]

p_library/urls.py
from django.contrib import admin  
from django.urls import path  
from .views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many, BookFriendList, BookFriendUpdate, FriendEdit
# from p_library import views

app_name = 'p_library'

urlpatterns = [  
    path('author/create', AuthorEdit.as_view(), name='author_create'),  
    path('authors', AuthorList.as_view(), name='author_list'),
    path('author/create_many', author_create_many, name='author_create_many'),
    path('author_book/create_many', books_authors_create_many, name='author_book_create_many'),
    path('book_friend_list/', BookFriendList.as_view(), name='book_friend_list'),
    path('book_friend_update/<int:pk>', BookFriendUpdate.as_view(), name='book_friend_update'),
    path('friend/create', FriendEdit.as_view(), name='friend_create'),
]

p_library/models.py
from django.db import models

class Author(models.Model):  
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)
    def __str__(self): return self.full_name

class Book(models.Model):  
    ISBN = models.CharField(max_length=13)  
    title = models.TextField()  
    description = models.TextField()  
    year_release = models.SmallIntegerField()  
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    copy_count = models.SmallIntegerField(default=1, blank=True, null=True)
    price = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=7)
    redaction = models.ForeignKey('Redaction', blank=True, null=True, on_delete=models.CASCADE, related_name='books')
    friend = models.ForeignKey('Friend', blank=True, null=True, on_delete=models.CASCADE, related_name='books')
    def __str__(self): return self.title

class Redaction(models.Model):
    name = models.CharField(max_length=128)
    def __str__(self): return self.name

class Friend(models.Model):
    name = models.CharField(max_length=40)
    def __str__(self): return self.name
    

p_library/forms.py
from django import forms
from p_library.models import Author, Book, Redaction, Friend
from django.forms import formset_factory 

class AuthorForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput)
    class Meta:
        fields = "__all__"
        model = Author

    
class BookForm(forms.ModelForm):
    class Meta:
        fields="__all__"
        model=Book

class FriendForm(forms.ModelForm):
    class Meta:
        fields="__all__"
        model=Friend

p_library/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.template import loader
from django.forms import formset_factory
from django.views.generic import CreateView, ListView, UpdateView
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from django.http.response import HttpResponseRedirect
from .models import Book, Author, Redaction, Friend
from p_library.forms import AuthorForm, BookForm, FriendForm


# Create your views here.

def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)

def index(request):
    template = loader.get_template('index.html')
    # books_count = Book.objects.all().count()
    books = Book.objects.all()
    biblio_data = {
    	"title": "мою библиотеку", 
    	# "books_count": books_count,
    	"books": books,}
    return HttpResponse(template.render(biblio_data, request))

@csrf_exempt
def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

@csrf_exempt
def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

def redactions(request):
    template = loader.get_template('redactions.html')
    redactions = Redaction.objects.all()
    data = {
        "redactions": redactions,
    }
    return HttpResponse(template.render(data, request))

class AuthorEdit(CreateView):  
    model = Author  
    form_class = AuthorForm  
    success_url = reverse_lazy('p_library:author_list')  
    template_name = 'author_edit.html'  
  
  
class AuthorList(ListView):  
    model = Author  
    template_name = 'authors_list.html'

AuthorFormSet = formset_factory(AuthorForm)

def author_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  #  Первым делом, получим класс, который будет создавать наши формы. Обратите внимание на параметр `extra`, в данном случае он равен двум, это значит, что на странице с несколькими формами изначально будет появляться 2 формы создания авторов.
    if request.method == 'POST':  #  Наш обработчик будет обрабатывать и GET и POST запросы. POST запрос будет содержать в себе уже заполненные данные формы
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  #  Здесь мы заполняем формы формсета теми данными, которые пришли в запросе. Обратите внимание на параметр `prefix`. Мы можем иметь на странице не только несколько форм, но и разных формсетов, этот параметр позволяет их отличать в запросе.
        if author_formset.is_valid():  #  Проверяем, валидны ли данные формы
            for author_form in author_formset:  
                author_form.save()  #  Сохраним каждую форму в формсете
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  #  После чего, переадресуем браузер на список всех авторов.
    else:  #  Если обработчик получил GET запрос, значит в ответ нужно просто "нарисовать" формы.
        author_formset = AuthorFormSet(prefix='authors')  #  Инициализируем формсет и ниже передаём его в контекст шаблона.
    return render(request, 'manage_authors.html', {'author_formset': author_formset})


def books_authors_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  
    BookFormSet = formset_factory(BookForm, extra=2)
    FriendFormSet = formset_factory(FriendForm, extra=2)
    if request.method == 'POST':  
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        friend_formset = FriendFormSet(request.POST, request.FILES, prefix='friends')  
        if author_formset.is_valid() and book_formset.is_valid() and friend_formset.is_valid():  
            for author_form in author_formset:  
                author_form.save()  
            for book_form in book_formset:  
                book_form.save()
            for friend_form in friend_formset:
                friend_form.save()  
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  
    else:  
        author_formset = AuthorFormSet(prefix='authors')  
        book_formset = BookFormSet(prefix='books')
        friend_formset = FriendFormSet(prefix='friends')  
    return render(
        request,  
        'manage_books_authors.html',  
        {  
            'author_formset': author_formset,  
            'book_formset': book_formset,
            'friend_formset': friend_formset,  
        }  
    )

class FriendEdit(CreateView):  
    model = Friend  
    form_class = FriendForm  
    success_url = reverse_lazy('p_library:book_friend_list')  
    template_name = 'friend_edit.html'


class BookFriendList(ListView):
    template_name = 'book_friend_list.html'
    context_object_name = "books"
    model = Book


class BookFriendUpdate(UpdateView):
    model = Book
    fields = ['title', 'author', 'description', 'friend']
    success_url = reverse_lazy('p_library:book_friend_list') 
    template_name = 'book_friend_update.html' 

p_library/templates/author_edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>Форма создания и редактирования авторов</title>  
</head>  
<body class="m-5">
<h1>Форма создания и редактирования авторов</h1> 
<form method="post" class="mt-5"> 
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" value="Сохранить" class='btn btn-primary'>  
</form>  
</body>  
</html>

p_library/templates/authors_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>Список авторов</title>
</head>
<body class="m-5">
<h1>Список авторов</h1>
	<ul>
		{% for author in object_list %}
		    <li>{{ author.full_name }}</li>
		{% endfor %}
	</ul>
</body>
</html>

p_library/templates/book_friend_list.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Books & Friends</title>
</head>
<body class="ml-5">
	<h1>Книги и друзья</h1>
	<ul class="list-group  list-group-flush">
		{% for book in books %}
		    <ul class="list-group"><h1 class="h4 text-left font-weight-bold mt-5">{{book.title}}</h1>
		    <li class="list-group-item">
		        <p class="font-italic">{{book.author}}</p> 
		        <p class="font-weight-light">{{book.description|truncatechars:200}}</p>
		    {% if book.friend %}
		    <p>Имя друга: <span class="badge badge-secondary">{{book.friend}}</span></p>
		    {% endif %}
		    <a class='btn btn-primary' href="{% url 'p_library:book_friend_update' book.id %}">Изменить книгу</a>
		    </ul>
		{% endfor %}
	</ul>
</body>

p_library/templates/book_friend_update.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8"> 
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
 <title>Форма редактирования авторов и книг</title>
<body class="m-5">
<form method="post" class="mt-5">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-primary">
</form>
</body>

p_library/templates/friend_edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>Форма для добавления друзей, которые берут в долг книги</title>  
</head>  
<body class="m-5">
<h1>Форма для добавления друзей, которые берут в долг книги</h1> 
<form method="post" class="mt-5"> 
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" value="Сохранить" class='btn btn-primary'>  
</form>  
</body>  
</html>

p_library/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>My library</title>
</head>
<body class="ml-5 mr-5">
	<h1>Добро пожаловать в {{ title }}.</h1>
	<br>
	<!-- <p>Тут собрано {{ books_count }} книг из моей личной коллекции.</p> -->
	<h2>Тут собрано {{ books|length }} книг из моей личной коллекции.</h2>
	<table border="1" class="table table-striped">
    	<thead>
    		<tr class="bg-warning">
      			<th scope="col">#</th>
      			<th scope="col">Title</th>
      			<th scope="col">ISNB</th>
      			<th scope="col">Description</th>
      			<th scope="col">Year release</th>
      			<th scope="col">Author</th>
      			<th scope="col">Country</th>
      			<th scope="col">Copy count</th>
      			<th scope="col">Change count</th>
    		</tr>
  		</thead>
  		{% for book in books %}
  		<tbody>
		    <tr>
		    	<td class="font-weight-bold">{{ forloop.counter }}</td>
		        <td class="font-weight-bold">{{ book.title }}</td>
		        <td>{{ book.ISBN }}</td>
		        <td>{{ book.description }}</td>
		        <td>{{ book.year_release }}</td>
		        <td>{{ book.author.full_name }}</td>
		        <td>{{ book.author.country }}</td>
		        <td>{{ book.copy_count }}</td>
		        <td>
	                <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
	                    {% csrf_token %}
	                    <input type="hidden" name="id" value="{{book.id}}" />
	                    <button class="btn btn-outline-success btn-sm btn-block my-1" type="submit">Увеличить кол-во</button>
	                </form>
	                <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
	                    {% csrf_token %}
	                    <input type="hidden" name="id" value="{{book.id}}" />
	                    <button class="btn btn-outline-danger btn-sm btn-block my-1" type="submit">Уменьшить кол-во</button>
	                </form>
	            </td>
		    </tr>
		</tbody>
	    {% endfor %}
	</table>
</body>
</html>

p_library/templates/manage_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <title>Create multiple authors</title>  
</head>  
<body class="m-5">
<h1>Форма создания нескольких авторов</h1>  
<form method="post" class="mt-5">  
	{% csrf_token %}  
	{% for form in author_formset %}  
		{{ form.as_ul }}  
		<br>  
	{% endfor %}
    <input type="submit" value="Сохранить" class='btn btn-primary'/>  
</form>  
</body>  
</html>

p_library/templates/manage_books_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8"> 
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
 <title>Create multiple Authors and Books</title>  
</head>  
<body class="m-5">
<h1>Форма создания нескольких книг и авторов</h1> 
<form method="post" class="mt-5">  
  {% csrf_token %}  
  {% for form in author_formset %}  
    {{ form.as_ul }}  
    <br>  
  {% endfor %}  
  
  {% for form in book_formset %}  
    {{ form.as_ul }}  
    <br>  
  {% endfor %}  
  <input type="submit" value="Сохранить" class="btn btn-primary"/>  
</form>  
</body>  
</html>

p_library/templates/redactions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Издательства и книги</title>
</head>
<body>
    <h1 class="text-secondary ml-5">Издательства и книги</h1>
    {% for redaction in redactions %}
        <ul class="list-group">
            <li class="list-group-item text-success">
                {{ redaction.name }}
                <ul class="list-group text-secondary">
                    {% for book in redaction.books.all %}
                        <li class="list-group-item"> {{ book.title }}</li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    {% endfor %}
</body>
</html>